// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * @package    mod_page
 * @copyright  2021 Adrian Stritzinger <Adrian.Stritzinger@studium.fernuni-hagen.de>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
export const GET = Object.freeze({
  ANNOTATION: 'ANNOTATION',
  ANNOTATION_FILTER: 'ANNOTATION_FILTER',
  ANNOTATION_WITH_CONTEXT: 'ANNOTATION_WITH_CONTEXT',
  ANNOTATIONS: 'ANNOTATIONS',
  BOOKMARKS: 'BOOKMARKS',
  CAN_USER_MOD_ANNOTATION: 'CAN_USER_MOD_ANNOTATION',
  FILTERED_ANNOTATIONS: 'FILTERED_ANNOTATIONS',
  FILTERED_THREADS: 'FILTERED_THREADS',
  HIGHLIGHTS: 'HIGHLIGHTS',
  LONGPAGE_CONTEXT: 'LONGPAGE_CONTEXT',
  NEW_ANNOTATION: 'NEW_ANNOTATION',
  NEW_POST: 'NEW_POST',
  NEW_THREAD: 'NEW_THREAD',
  POST: 'POST',
  POST_LAST_MODIFIED: 'POST_LAST_MODIFIED',
  POSTS: 'POSTS',
  SCROLL_TOP: 'SCROLL_TOP',
  SELECTED_THREAD_COMP_FUNC_FOR_SORT: 'GET_SELECTED_THREAD_COMP_FUNC_FOR_SORT',
  SELECTED_THREAD_SORTING_OPTION: 'GET_SELECTED_THREAD_SORTING_OPTION',
  SIDEBAR_TAB_OPENED_KEY: 'SIDEBAR_TAB_OPENED_KEY',
  THREAD: 'THREAD',
  THREAD_FILTER: 'THREAD_FILTER',
  THREAD_SORTING_OPTIONS: 'THREAD_SORTING_OPTIONS',
  THREADS: 'THREADS',
  THREADS_FILTERED: 'THREADS_FILTERED',
  THREADS_SORTED_BY_ANNOTATION_POSITION: 'THREADS_SORTED_BY_ANNOTATION_POSITION',
  USER: 'USER',
  USER_ROLES: 'USER_ROLES',
  USERS: 'USERS',
});

export const MUTATE = Object.freeze({
  ADD_ANNOTATIONS: 'ADD_ANNOTATIONS',
  ADD_POSTS_TO_THREAD: 'ADD_POST_TO_THREAD',
  ADD_THREADS: 'ADD_THREADS',
  POST_LAST_MODIFIED: 'POST_LAST_MODIFIED',
  REMOVE_ANNOTATIONS: 'REMOVE_ANNOTATIONS',
  REMOVE_POSTS_FROM_THREAD: 'REMOVE_POST',
  REMOVE_THREADS: 'REMOVE_THREADS',
  REPLACE_POST: 'REPLACE_POST',
  RESET_SCROLL_TOP: 'RESET_SCROLL_TOP',
  SELECTED_THREAD_SORTING_OPTION: 'MUTATE_SELECTED_THREAD_SORTING_OPTION',
  SET_ANNOTATION_FILTER: 'RESET_ANNOTATION_FILTER',
  SET_ANNOTATIONS: 'SET_ANNOTATIONS',
  SET_ENROLLED_USERS: 'SET_ENROLLED_USERS',
  SET_FILTERED_ANNOTATIONS: 'SET_FILTERED_ANNOTATIONS',
  SET_FILTERED_THREADS: 'SET_FILTERED_THREADS',
  SET_THREAD_FILTER: 'SET_THREAD_FILTER',
  SET_THREADS: 'SET_THREADS',
  SET_USER_ROLES: 'SET_USER_ROLES',
  SET_USER_CAN_MOD_ANNOTATION: 'SET_USER_CAN_MOD_ANNOTATION',
  RESET_SIDEBAR_TAB_OPENED_KEY: 'RESET_SIDEBAR_TAB_OPENED_KEY',
  UPDATE_ANNOTATION: 'UPDATE_ANNOTATION',
  UPDATE_POST: 'UPDATE_POST',
  UPDATE_SCROLL_TOP: 'UPDATE_SCROLL_TOP',
  UPDATE_THREAD: 'UPDATE_THREAD',
});

export const ACT = Object.freeze({
  CREATE_ANNOTATION: 'CREATE_ANNOTATION',
  CREATE_POST: 'CREATE_POST',
  DELETE_ANNOTATION: 'DELETE_ANNOTATION',
  DELETE_POST: 'DELETE_POST',
  FETCH_ANNOTATIONS: 'FETCH_ANNOTATIONS',
  FETCH_ENROLLED_USERS: 'FETCH_ENROLLED_USERS',
  FETCH_USER_ROLES: 'FETCH_USER_ROLES',
  FILTER_ANNOTATIONS: 'FILTER_ANNOTATIONS',
  FILTER_THREADS: 'FILTER_THREADS',
  REPLACE_OR_ADD_ANNOTATION: 'REPLACE_OR_ADD_ANNOTATION',
  REPLACE_OR_ADD_POST: 'REPLACE_OR_ADD_POST',
  REPLACE_OR_ADD_THREAD: 'REPLACE_OR_ADD_THREAD',
  SELECT_ANNOTATIONS: 'SELECT_ANNOTATIONS',
  TOGGLE_POST_BOOKMARK: 'TOGGLE_POST_BOOKMARK',
  TOGGLE_POST_LIKE: 'TOGGLE_POST_LIKE',
  TOGGLE_POST_READING: 'TOGGLE_POST_READING',
  TOGGLE_THREAD_SUBSCRIPTION: 'TOGGLE_THREAD_SUBSCRIPTION',
  UPDATE_ANNOTATION: 'UPDATE_ANNOTATION',
  UPDATE_POST: 'UPDATE_POST',
  UPDATE_READING_PROGRESS: 'UPDATE_READING_PROGRESS',
  USER_CAN_MOD_ANNOTATION: 'USER_CAN_MOD_ANNOTATION',
});
